### ISSUE TITLE
Failed to make PR, access denied to user

### ISSUE THREAD

**Issue by NateOs** [codediodeio/gimmie-sticker#334]
Permission to codediodeio/gimmie-sticker.git denied to NateOs.

Perhaps it's because this repo is two years old and gets no more attention.
Thanks for your videos though.

**Comment by ghost** [comment]
You have to create a fork first, try clicking [here](https://github.com/codediodeio/gimmie-sticker/fork).

**Comment by NateOs** [comment]
I already did, can't make a PR without making the fork to modify the code first

**Comment by LastGentlman** [comment]
Did u solve it? i had no problems at all it  is a good practice
